apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sleep
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  strategy: {}
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command: command: ["sleep", "infinity"]
        resources: {}
